{{- if and (.Values.networkPolicies.enabled) (.Values.networkPolicies.egress.deny.all) }}
{{- range $name, $tenant := .Values.namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    {{- include "team.annotations" $ | nindent 4 }}
    {{- if $.Values.networkPolicies.annotations }}
    {{- with $.Values.networkPolicies.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "team.labels" $ | nindent 4 }}
    {{- if $.Values.networkPolicies.labels }}
    {{- with $.Values.networkPolicies.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  name: {{ include "team.networkPolicy.egress.deny.all.name" $ | quote }}
  namespace: {{ $name }}
spec:
  {{- if $.Values.networkPolicies.egress.deny.all.podSelector }}
  podSelector:
    {{- toYaml $.Values.networkPolicies.egress.deny.all.podSelector | nindent 4 }}
  {{- else }}
  podSelector: {}
  {{- end }}
  policyTypes:
    - Egress
  egress: []
{{- end }}
{{- end }}